### ISSUE TITLE
Error occurring

### ISSUE THREAD

**Issue by Sleepvvalker00** [griffisben/Wyscout_Prospect_Research#3]
The website 
https://football-prospect-research-made-by-bengriffis.streamlit.app/
continuously has an error when I try to open it. Is there something I can do about it?:)
Thanks in advance<3

**Comment by griffisben** [comment]
Sorry, Streamlit can get quite unstable when there's decent amounts of traffic, consistently... I think that's the problem! I've been slower to detect the crashes since it's around the holidays for me, but am rebooting now and can check more frequently.
